# Generated by Django 2.2.7 on 2019-12-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', 'Administrador'), ('2', 'Usuario')], default='2', max_length=1),
        ),
    ]
