# Generated by Django 2.2.7 on 2019-12-07 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
