# Generated by Django 2.2.7 on 2019-12-08 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20191208_0135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rol',
            new_name='Role',
        ),
    ]
