# Generated by Django 2.2.7 on 2019-12-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=1000)),
                ('createDate', models.DateField()),
                ('status', models.CharField(default='1', max_length=1)),
            ],
        ),
    ]
