# Generated by Django 2.2.7 on 2019-12-08 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_comment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='category',
        ),
        migrations.RemoveField(
            model_name='file',
            name='content',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
