# Generated by Django 2.2.7 on 2019-12-08 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('extension', models.CharField(max_length=30)),
                ('uploadDate', models.DateField()),
                ('status', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Content')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('createDate', models.DateField()),
                ('status', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Content')),
            ],
        ),
    ]
